name: Prod build and deployment
on:
  push:
    branches:
      - 'origin/master'
jobs:
  BuildSimulation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Release Manager
        id: check_release_manager
        run: |
          if [[ "${{ github.actor }}" != "AmiranIV" ]]; then
            echo "Workflow aborted. Only the release manager can trigger this workflow."
            exit 1
          fi
      - name: Build
        run: |
          echo "Building and packing an app..."
  DeploySimulation:
    runs-on: ubuntu-latest
    needs: BuildSimulation
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          echo "Deploying into Test environment"
